import img_1 from '../assets/img/blogs/article-1.png';
import img_2 from '../assets/img/blogs/article-2.png';
import img_3 from '../assets/img/blogs/article-3.png';

export const blogData = [
  {
    id: '1',
    thumb: img_1,
    title: 'The actual history of machine intelligence',
    desc: '',
    date: 'March 18, 2022',
    author: '',
    link: '/blog-details',
    commentCount: 1,
  },
  {
    id: '2',
    thumb: img_2,
    title: 'The actual history of machine intelligence',
    desc: '',
    date: 'March 18, 2022',
    author: '',
    link: '/blog-details',
    commentCount: 2,
  },
  {
    id: '3',
    thumb: img_3,
    title: 'The actual history of machine intelligence',
    desc: '',
    date: 'March 18, 2022',
    author: '',
    link: '/blog-details',
    commentCount: 3,
  },
  {
    id: '4',
    thumb: img_1,
    title: 'The actual history of machine intelligence',
    desc: '',
    date: 'March 18, 2022',
    author: '',
    link: '/blog-details',
    commentCount: 4,
  },
  {
    id: '5',
    thumb: img_2,
    title: 'The actual history of machine intelligence',
    desc: '',
    date: 'March 18, 2022',
    author: '',
    link: '/blog-details',
    commentCount: 5,
  },
  {
    id: '6',
    thumb: img_3,
    title: 'The actual history of machine intelligence',
    desc: '',
    date: 'March 18, 2022',
    author: '',
    link: '/blog-details',
    commentCount: 6,
  },
];
